site_name: Consumer Complaint Database search API

nav:
- What's available in the API?: index.md

theme:
    name: mkDOCter
extra:
    brand_color: "#2CB34A"
    logo_url: https://cfpb.github.io/img/logo_210.png
    logo_alt: Consumer Financial Protection Bureau

markdown_extensions:
    - admonition
    - tables
